import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const json = (p) => JSON.parse(read(p));
const manifest = json('data/manifest.json');
const questions = json('data/questions.json');
const cases = json('data/cases.json');
const index = read('index.html');
const sw = read('service-worker.js');
const mix = read('js/p17-study-mix.js');
const core = read('js/p17-study-mix-core.js');
const bootstrap = read('js/p17-bootstrap.js');

assert.equal(manifest.phase, 'P17');
assert.equal(manifest.version, '1.1.0-dev.17');
assert.equal(manifest.status, 'p17-adaptive-study-mix-v2');
assert.equal(questions.length, 954);
assert.equal(cases.length, 120);
assert(index.includes('./js/p17-bootstrap.js'));
assert(!index.includes('./js/p16-bootstrap.js'));
assert(bootstrap.includes('installExamPlanPatches'));
assert(bootstrap.includes('installAdaptiveMixPatches'));
assert(bootstrap.indexOf('installExamPlanPatches') < bootstrap.indexOf('installAdaptiveMixPatches'));
assert(bootstrap.includes("import('./app.js')"));
assert(sw.includes('pflegelern-p17-v1.1.0-dev17'));
for (const asset of ['./js/p17-study-mix-core.js','./js/p17-study-mix.js','./js/p17-bootstrap.js']) assert(sw.includes(asset));
assert(mix.includes('previousSelectRecommended'));
assert(mix.includes('previousPreview'));
assert(mix.includes('isDue'));
assert(!mix.includes('scheduleReview'));
assert(!mix.includes("db.put('cardState'"));
assert(core.includes('coverageDebt'));
assert(core.includes('applicationDebt'));
assert(core.includes('questionAgeDays'));
assert(core.includes('conceptAgeDays'));
assert(core.includes('collisionWindow'));
assert(core.includes('maxConsecutiveQuestions'));
assert(mix.includes('weaknessScore'));
assert(mix.includes('conceptSeen'));
assert(mix.includes('inExamScope'));
assert(mix.includes('questionHistory'));
assert(mix.includes('prepareQuestionItem'));
assert(index.includes('<span>Heute</span>') && index.includes('<span>Lernen</span>') && index.includes('<span>Prüfung</span>') && index.includes('<span>Fortschritt</span>'));
assert(!index.includes('XP') && !index.includes('Streak'));

console.log(JSON.stringify({ phase:'P17', integrationAssertions:31, errors:0 }, null, 2));
