import assert from 'node:assert/strict';
import fs from 'node:fs';

let tests = 0;
const check = (fn) => { fn(); tests += 1; };
const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

const bootstrap = read('js/p18-bootstrap.js');
const core = read('js/p20-exam-core.js');
const runtime = read('js/p20-exam.js');
const ui = read('js/p20-exam-ui.js');
const css = read('css/p20-exam.css');
const sw = read('service-worker.js');
const manifest = JSON.parse(read('data/manifest.json'));
const p19 = read('js/p19-remediation.js');
const p18 = read('js/p18-mastery.js');
const storage = read('js/storage.js');
const app = read('js/app.js');

check(() => assert.match(bootstrap, /installMockExamPatches/));
check(() => assert.match(bootstrap, /initMockExamUi/));
check(() => assert.match(bootstrap, /installWeaknessRemediationPatches\(\);[\s\S]*installMockExamPatches\(\);/));
check(() => assert.match(bootstrap, /await import\('\.\/app\.js'\);[\s\S]*initMockExamUi\(\);/));
check(() => assert.match(runtime, /previousFinalize\.call\(this, attempt\)/));
check(() => assert.match(runtime, /EXAM_PLAN_SETTING_KEY/));
check(() => assert.match(runtime, /objectiveQuestionType/));
check(() => assert.match(runtime, /timerEnabled/));
check(() => assert.match(runtime, /deadlineAt/));
check(() => assert.match(runtime, /chapterIds/));
check(() => assert.match(runtime, /p20ExamOverview/));
check(() => assert.match(core, /answer\.order/));
check(() => assert.match(ui, /Fragenübersicht/));
check(() => assert.match(ui, /Meine Schwächen/));
check(() => assert.match(ui, /Kapitel auswählen/));
check(() => assert.match(ui, /Timer verwenden/));
check(() => assert.match(ui, /Lösungen erscheinen erst nach Abgabe/));
check(() => assert.match(ui, /data-signature/));
check(() => assert.match(ui, /handleExamSubmitCapture/));
check(() => assert.match(ui, /Fehler gezielt lernen/));
check(() => assert.match(ui, /Trainingsziel erreicht/));
check(() => assert.match(css, /p20-question-grid/));
check(() => assert.doesNotMatch(css, /--surface-strong/));
check(() => assert.match(sw, /pflegelern-p20-v1\.1\.0-dev20/));
check(() => assert.match(sw, /\.\/js\/p20-exam-core\.js/));
check(() => assert.match(sw, /\.\/js\/p20-exam\.js/));
check(() => assert.match(sw, /\.\/js\/p20-exam-ui\.js/));
check(() => assert.match(sw, /\.\/css\/p20-exam\.css/));
check(() => assert.equal(manifest.phase, 'P20'));
check(() => assert.equal(manifest.version, '1.1.0-dev.20'));
check(() => assert.equal(manifest.status, 'p20-mock-exam-system-v2'));
check(() => assert.ok(manifest.notes.some((x) => x.startsWith('P20 '))));
check(() => assert.match(p19, /createExamReviewSession/));
check(() => assert.match(p19, /Fehler gezielt lernen/));
check(() => assert.match(p18, /source === 'exam'/));
check(() => assert.match(storage, /examAttempts/));
check(() => assert.match(storage, /DB_VERSION = 2/));
check(() => assert.match(app, /Lösungen siehst du erst am Ende/));
check(() => assert.match(app, /markedForReview/));
check(() => assert.doesNotMatch(runtime, /scheduleReview\(/));
check(() => assert.doesNotMatch(runtime, /cardState/));

console.log(JSON.stringify({ phase: 'P20-integration', tests, errors: 0 }, null, 2));
